### ISSUE TITLE
can't get performance result on kth

### ISSUE THREAD

**Issue by xiaomingdujin** [google/e3d_lstm#13]
Hello, thank you for the paper and releasing the code. I run the test on the kth action dataset uising the downloaded the pre-trained weights, but I can't get the results of the paper which report on the kth task.
Maybe it's my parameters or I am not running it the right way?

![pd11](https://user-images.githubusercontent.com/31694917/84585770-a73d2480-ae45-11ea-8c4a-058e68947b74.png)
![pd12](https://user-images.githubusercontent.com/31694917/84585778-bfad3f00-ae45-11ea-92ce-4698d26c8911.png)
![pd13](https://user-images.githubusercontent.com/31694917/84585779-c1770280-ae45-11ea-948e-1e3addf8e522.png)
![pd14](https://user-images.githubusercontent.com/31694917/84585780-c2a82f80-ae45-11ea-999d-6682396b83cd.png)
![pd15](https://user-images.githubusercontent.com/31694917/84585781-c340c600-ae45-11ea-9dda-cb0b0956f4a7.png)

**Comment by wyb15** [comment]
Hi Jinming,

You are right. It should return "new_global_memory" in Line 217 in "e3d_lstm/src/layers/rnn_cell.py", instead of "global_memory". It is the reason why you and some others cannot get the performance reported in the paper. 

We noticed that this bug only appeared in the code repo, which was revised and reproduced in accordance with company policy after the paper was accepted. This did not exist in our original experiments, so the results reported in the paper are good.

We are fixing the code and will re-upload the pre-trained models. We apologize for the inconvenience and thank you for your patience. 

Best,
Yunbo

**Comment by roadjiang** [comment]
Duplicated issue. Please refer to the following one for future discussions:
https://github.com/google/e3d_lstm/issues/1
